### ISSUE TITLE
Running Plugin raises AttributeError: 'float' object has no attribute 'AsTenthsOfADegree'

### ISSUE THREAD

**Issue by dm2lct** [MitjaNemec/PlaceFootprints#22]
Under Kicad 6.0.11 under Debian 12 the plugin seems not to work.

It raises a fatal error when trying to run it:

  * I selected a Footprint from a hierachical schematic
  * opened the plugin config and set it to matrix and 6 columns
  * left everything else untouched
  * ran it

Then the attached error message came. 

In the log there is a python error raised.

The same issue occoured when trying to tun the replicate layout plugin.

I hope this is enough for describing the error. 

Thanks a lot for your work!

![2024_03_27-13_51_29](https://github.com/MitjaNemec/PlaceFootprints/assets/33619558/f2882f2d-cadf-4df9-9c0d-773c623b3f6b)

![2024_03_27-13_53_32](https://github.com/MitjaNemec/PlaceFootprints/assets/33619558/ff0973ee-0255-43fd-a8a2-aab3b22da228)

[place_footprints.log](https://github.com/MitjaNemec/PlaceFootprints/files/14773547/place_footprints.log)

**Comment by MitjaNemec** [comment]
Yeah, that is the same as issue #14 and [#47](https://github.com/MitjaNemec/ReplicateLayout/issues/47) and [#56](https://github.com/MitjaNemec/ReplicateLayout/issues/56) in the ReplicateLayout plugin.

The bug is within "PcbnewTransition", which was installed as a dependency of some other plugin. Either update "PcbnewTransition" or remove it.

**Comment by dm2lct** [comment]
Thanks a lot! 
After I deinstalled KiKit and deleted ./.local/lib/python3.11/site-packages/pcbnewTransition
everything works perfectly.
